version: '3.7'
services:
    postgres:
        image: postgres:11
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_DB=trivia
          - POSTGRES_USER=flaskr
          - POSTGRES_PASSWORD=trivia-app

    test_pg:
        image: postgres:11
        ports:
          - "54321:5432"
        environment:
          - POSTGRES_DB=trivia_test
          - POSTGRES_USER=test
          - POSTGRES_PASSWORD=test
          - POSTGRES_HOST_AUTH_METHOD=trust
